name: Publish to NPM
on:
  push:
#    tags:
#      - v[0-9]+\.[0-9]+\.[0-9]+
    branches:
      - '**'

jobs:
  publish:
    if: ${{ github.ref == 'refs/heads/master' }}
    runs-on: ubuntu-latest
    steps:
      - name: Get sources
        uses: actions/checkout@v2

      - name: Read .nvmrc for Node.js version
        run: echo ::set-output name=NODE_VERSION::$(cat .nvmrc)
        id: nvm

      - name: Publish to NPM
        uses: actions/setup-node@v2
        with:
          node-version: '${{ steps.nvm.outputs.NODE_VERSION }}'
          registry-url: 'https://registry.npmjs.org'
          scope: '@waves'
      - run: npm install
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}
